<?php

declare(strict_types=1);

return [
    'customer_intake' => [
        'first_name' => [
            'label' => 'Imię klienta',
            'description' => 'Wpisz pierwsze imię klienta zgodnie z dokumentem tożsamości. W przypadku firm wpisz imię osoby kontaktowej.',
            'example' => 'Jan',
            'validation' => 'Minimum 2 znaki, wyłącznie litery.',
            'roles' => ['Recepcja', 'Administrator'],
        ],
        'last_name' => [
            'label' => 'Nazwisko klienta',
            'description' => 'Nazwisko klienta lub osoby kontaktowej. Jeśli klientem jest firma, wpisz nazwę firmy w polu "Firma".',
            'example' => 'Kowalski',
            'validation' => 'Minimum 2 znaki, wyłącznie litery.',
            'roles' => ['Recepcja', 'Administrator'],
        ],
        'email' => [
            'label' => 'Adres e-mail',
            'description' => 'Adres e-mail do komunikacji z klientem. Preferowany adres firmowy dla klientów biznesowych.',
            'example' => 'serwis@firma.pl',
            'validation' => 'Format e-mail, wymagany dla klientów biznesowych.',
            'roles' => ['Recepcja', 'Koordynator', 'Administrator'],
        ],
        'phone' => [
            'label' => 'Telefon kontaktowy',
            'description' => 'Numer telefonu z prefiksem kraju. Potrzebny do powiadomień SMS.',
            'example' => '+48 600 700 800',
            'validation' => '9-15 cyfr, dopuszczalne spacje.',
            'roles' => ['Recepcja', 'Koordynator', 'Administrator'],
        ],
        'consents' => [
            'label' => 'Zgody i oświadczenia',
            'description' => 'Zaznacz wszystkie zgody podpisane przez klienta (RODO, przetwarzanie haseł, zgoda na kontakt marketingowy).',
            'example' => 'RODO, Zgoda na hasło',
            'validation' => 'Co najmniej RODO przy nowych klientach.',
            'roles' => ['Recepcja', 'Administrator'],
        ],
    ],
    'device_intake' => [
        'device_type' => [
            'label' => 'Typ urządzenia',
            'description' => 'Wybierz kategorię urządzenia z listy. Jeśli nie ma odpowiedniej pozycji, wybierz "Inne" i dodaj opis w notatkach.',
            'example' => 'Laptop',
            'validation' => 'Pole wymagane.',
            'roles' => ['Recepcja', 'Technik', 'Administrator'],
        ],
        'manufacturer' => [
            'label' => 'Producent',
            'description' => 'Producent urządzenia z tabliczki znamionowej.',
            'example' => 'Dell',
            'validation' => 'Pole wymagane, 2-50 znaków.',
            'roles' => ['Recepcja', 'Technik', 'Administrator'],
        ],
        'model' => [
            'label' => 'Model',
            'description' => 'Dokładny model urządzenia, np. oznaczenie na obudowie lub pod baterią.',
            'example' => 'Latitude 5510',
            'validation' => 'Pole wymagane, dopuszczalne litery, cyfry, myślnik.',
            'roles' => ['Recepcja', 'Technik', 'Administrator'],
        ],
        'serial_number' => [
            'label' => 'Numer seryjny',
            'description' => 'Przepisz numer seryjny z tabliczki producenta lub BIOS. W razie braku zaznacz opcję "brak" i dodaj notatkę.',
            'example' => 'SN123456789',
            'validation' => '6-30 znaków, litery i cyfry.',
            'roles' => ['Recepcja', 'Technik', 'Administrator'],
        ],
        'password' => [
            'label' => 'Hasło / PIN',
            'description' => 'Jeżeli klient udostępnił hasło do urządzenia, wpisz je tutaj. Hasło zostanie zaszyfrowane i dostępne tylko dla technika.',
            'example' => 'P@ssw0rd!',
            'validation' => 'Pole opcjonalne, przechowywane w szyfrowanej formie.',
            'roles' => ['Technik', 'Administrator'],
        ],
        'accessories' => [
            'label' => 'Akcesoria',
            'description' => 'Wymień wszystkie akcesoria oddane z urządzeniem (zasilacz, torba, mysz).',
            'example' => 'Zasilacz 65W, mysz USB',
            'validation' => 'Tekst do 255 znaków.',
            'roles' => ['Recepcja', 'Technik', 'Administrator'],
        ],
    ],
    'repair_order' => [
        'issue_description' => [
            'label' => 'Opis problemu',
            'description' => 'Opisz zgłaszany problem słowami klienta. Dodaj dodatkowe obserwacje, jeśli są dostępne.',
            'example' => 'Laptop nie uruchamia się, dioda zasilania miga na pomarańczowo.',
            'validation' => 'Pole wymagane, min. 10 znaków.',
            'roles' => ['Recepcja', 'Technik', 'Administrator'],
        ],
        'diagnosis' => [
            'label' => 'Diagnoza wstępna',
            'description' => 'Wpisz wnioski technika po wstępnych testach. Jeśli diagnoza nie została jeszcze wykonana, wpisz "Do ustalenia".',
            'example' => 'Uszkodzona sekcja zasilania płyty głównej.',
            'validation' => 'Pole wymagane przed przejściem do statusu "W naprawie".',
            'roles' => ['Technik', 'Administrator'],
        ],
        'priority' => [
            'label' => 'Priorytet',
            'description' => 'Wybierz priorytet SLA zgodnie z umową (Standard, Pilne, Krytyczne).',
            'example' => 'Pilne',
            'validation' => 'Pole wymagane, jedna z wartości słownikowych.',
            'roles' => ['Technik', 'Koordynator', 'Administrator'],
        ],
        'assigned_to' => [
            'label' => 'Przypisany technik',
            'description' => 'Wybierz technika odpowiedzialnego za zlecenie. Lista zawiera dostępnych pracowników zgodnie z modułem pracowników.',
            'example' => 'Anna Nowak',
            'validation' => 'Pole wymagane.',
            'roles' => ['Koordynator', 'Administrator'],
        ],
        'parts' => [
            'label' => 'Części',
            'description' => 'Dodaj części potrzebne do naprawy. System zweryfikuje dostępność w magazynie.',
            'example' => 'Płyta główna Dell P/N 0XYZ123',
            'validation' => 'Co najmniej jedna część, gdy status "Oczekuje na części".',
            'roles' => ['Technik', 'Magazynier', 'Administrator'],
        ],
    ],
    'appointment' => [
        'start_time' => [
            'label' => 'Data i godzina rozpoczęcia',
            'description' => 'Wybierz termin rozpoczęcia wizyty. System sugeruje najbliższe dostępne sloty.',
            'example' => '2024-05-20 10:00',
            'validation' => 'Pole wymagane, format RRRR-MM-DD GG:MM.',
            'roles' => ['Koordynator', 'Recepcja', 'Administrator'],
        ],
        'end_time' => [
            'label' => 'Data i godzina zakończenia',
            'description' => 'Podaj planowaną godzinę zakończenia. Dodaj bufor na ewentualne opóźnienia.',
            'example' => '2024-05-20 11:30',
            'validation' => 'Musi być późniejsze od start_time.',
            'roles' => ['Koordynator', 'Administrator'],
        ],
        'location' => [
            'label' => 'Lokalizacja',
            'description' => 'Wybierz lokalizację wizyty: serwis, wyjazd do klienta lub zdalnie.',
            'example' => 'Serwis - Stanowisko 3',
            'validation' => 'Pole wymagane.',
            'roles' => ['Koordynator', 'Recepcja', 'Administrator'],
        ],
        'resources' => [
            'label' => 'Zasoby',
            'description' => 'Dodaj zasoby wymagane do wizyty (stanowisko, samochód, urządzenia zastępcze).',
            'example' => 'Samochód 1, Stanowisko B',
            'validation' => 'Co najmniej jeden zasób przy wizytach wyjazdowych.',
            'roles' => ['Koordynator', 'Administrator'],
        ],
        'customer_confirmation' => [
            'label' => 'Potwierdzenie klienta',
            'description' => 'Zaznacz, gdy klient potwierdził termin. System wysyła przypomnienie 24h przed wizytą.',
            'example' => 'Potwierdzone telefonicznie',
            'validation' => 'Pole wymagane przed zmianą statusu na "Potwierdzone".',
            'roles' => ['Koordynator', 'Recepcja', 'Administrator'],
        ],
    ],
    'employee_profile' => [
        'full_name' => [
            'label' => 'Imię i nazwisko',
            'description' => 'Wpisz pełne dane identyfikacyjne. Używane w raportach i kalendarzu.',
            'example' => 'Anna Nowak',
            'validation' => 'Pole wymagane, minimum 3 znaki.',
            'roles' => ['Administrator', 'HR'],
        ],
        'email' => [
            'label' => 'Adres e-mail',
            'description' => 'Adres służbowy do powiadomień i logowania. Jeżeli pracownik nie korzysta z e-maila, pozostaw puste.',
            'example' => 'anna.nowak@digivriend.nl',
            'validation' => 'Format e-mail, unikalny w systemie.',
            'roles' => ['Administrator', 'HR'],
        ],
        'phone' => [
            'label' => 'Telefon kontaktowy',
            'description' => 'Numer wykorzystywany do powiadomień SMS i kontaktu w nagłych przypadkach.',
            'example' => '+31 6 1234 5678',
            'validation' => 'Pole opcjonalne, 9-15 cyfr.',
            'roles' => ['Administrator', 'HR'],
        ],
        'role' => [
            'label' => 'Rola systemowa',
            'description' => 'Określ dostęp systemowy: recepcja, technik, koordynator, administrator.',
            'example' => 'Technik',
            'validation' => 'Pole wymagane.',
            'roles' => ['Administrator'],
        ],
        'permissions' => [
            'label' => 'Uprawnienia szczegółowe',
            'description' => 'Zaznacz dodatkowe zakresy dostępu (magazyn, dokumenty, kalendarz).',
            'example' => 'calendar.manage, documents.publish',
            'validation' => 'Przynajmniej jedno uprawnienie dla ról koordynujących.',
            'roles' => ['Administrator'],
        ],
    ],
    'employee_availability' => [
        'type' => [
            'label' => 'Typ dostępności',
            'description' => 'Wybierz powód nieobecności lub tryb pracy. Informacja wyświetlana w kalendarzu.',
            'example' => 'Urlop, Szkolenie, Praca zdalna',
            'validation' => 'Pole wymagane.',
            'roles' => ['Koordynator', 'HR', 'Administrator'],
        ],
    ],
    'inventory' => [
        'part_code' => [
            'label' => 'Kod części',
            'description' => 'Unikalny kod magazynowy. Używany w kodach kreskowych i dokumentach PZ/WZ.',
            'example' => 'RAM-16GB-3200',
            'validation' => 'Pole wymagane, litery, cyfry, myślnik.',
            'roles' => ['Magazynier', 'Administrator'],
        ],
        'quantity' => [
            'label' => 'Ilość',
            'description' => 'Aktualna liczba sztuk na stanie. Aktualizowana automatycznie przy wydaniach i przyjęciach.',
            'example' => '12',
            'validation' => 'Wartość całkowita ≥ 0.',
            'roles' => ['Magazynier', 'Administrator'],
        ],
        'min_threshold' => [
            'label' => 'Stan minimalny',
            'description' => 'Minimalny poziom zapasu. System wyśle alert, gdy stan spadnie poniżej tej wartości.',
            'example' => '5',
            'validation' => 'Wartość całkowita ≥ 0.',
            'roles' => ['Magazynier', 'Koordynator', 'Administrator'],
        ],
        'supplier' => [
            'label' => 'Dostawca',
            'description' => 'Główny dostawca części. Wybierz z listy lub dodaj nowego w module dostawców.',
            'example' => 'ABC IT Distribution',
            'validation' => 'Pole opcjonalne.',
            'roles' => ['Magazynier', 'Administrator'],
        ],
    ],
    'document' => [
        'template' => [
            'label' => 'Szablon dokumentu',
            'description' => 'Wybierz szablon pasujący do generowanego dokumentu (np. protokół, faktura).',
            'example' => 'Protokoł przyjęcia v2',
            'validation' => 'Pole wymagane.',
            'roles' => ['Recepcja', 'Technik', 'Magazynier', 'Księgowość', 'Administrator'],
        ],
        'sign_method' => [
            'label' => 'Metoda podpisu',
            'description' => 'Wskaż sposób podpisania dokumentu (podpis cyfrowy, SMS, ręczny).',
            'example' => 'SMS - kod 4 cyfry',
            'validation' => 'Wymagane dla dokumentów wymagających podpisu klienta.',
            'roles' => ['Recepcja', 'Technik', 'Księgowość', 'Administrator'],
        ],
    ],
];